openapi: 3.0.3
info:
  description: "The BVNK API is designed to facilitate seamless and secure transactions\
    \ including payments, channels, anddigital wallet transactions."
  title: BVNK API Endpoints
  version: 1.0.1
servers:
- description: Sandbox
  url: https://api.sandbox.bvnk.com
- description: Production
  url: https://api.bvnk.com
tags:
- name: Currencies
- name: Merchant IDs
- name: Payments
- name: Channels
- name: Wallets
- name: Trading and Conversions
paths:
  /api/currency/crypto:
    get:
      description: |-
        Retrieves a list of all cryptocurrencies available on the BVNK platform. This list represents cryptocurrencies that end users can select whilst making a payment.

        For sandbox, only Ethereum (ETH) is fully functional.
      operationId: listCurrenciesCrypto
      summary: List Crypto Currencies
      tags:
      - Currencies
      x-accepts: application/json
  /api/currency/fiat:
    get:
      description: |-
        Retrieves a list of all display fiat currencies available on BVNK's Crypto Payments API.
        This list refers to currencies merchants can display on a payment page to an end user. It does not represent the list of currencies that can be held on the platform in wallets.
      operationId: listCurrenciesFiat
      summary: List Fiat Currencies
      tags:
      - Currencies
      x-accepts: application/json
  /api/currency/deposit:
    get:
      description: These are the currencies that can be used to create a new wallet.
      operationId: listCurrenciesDeposit
      summary: List Wallet Currencies
      tags:
      - Currencies
      x-accepts: application/json
  /api/v1/merchant:
    get:
      description: Retrieves merchant IDs setup on your account.
      operationId: merchantIdList
      security:
      - Hawk:
        - merchant
      summary: List Merchant IDs
      tags:
      - Merchant IDs
      x-accepts: application/json
    post:
      description: |-
        Generate a Merchant ID for your account to process pay-ins and pay-outs through our API.

        A Merchant ID is essential as it designates the account wallet where incoming pay-ins will be settled. For instance, if a Merchant ID is associated with a EUR wallet ID, any incoming USDT payment will be automatically converted to EUR and deposited in the designated EUR wallet.

        Vice versa, any outgoing USDT payment will be automatically converted and withdrawn from the designated EUR wallet.

        For further information, please visit https://docs.bvnk.com/docs/creating-your-first-merchant to learn more about creating your first Merchant ID.
      operationId: merchantIdCreate
      security:
      - Hawk:
        - merchant
      summary: Create Merchant ID
      tags:
      - Merchant IDs
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/pay/summary:
    get:
      description: Retrieves a list of payments on a specific Merchant ID
      security:
      - Hawk:
        - merchant
      summary: List Payments
      tags:
      - Payments
      x-accepts: application/json
    post:
      description: "Creates a payment, either type IN or type OUT."
      security:
      - Hawk:
        - merchant
      summary: Create payment
      tags:
      - Payments
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/pay/{uuid}/summary:
    get:
      description: Retrieves details of a specific payment using the UUID of the payment.
      security:
      - Hawk:
        - merchant
      summary: Get Payment
      tags:
      - Payments
      x-accepts: application/json
  /api/v1/pay/validate:
    put:
      description: |-
        Validates that a crypto address is correct.

        Use this endpoint to validate that an address exists, is correctly formatted, and includes all the required data. This endpoint can help prevent your end users losing funds when submitting a payout.
      summary: Validate Address
      tags:
      - Payments
      x-content-type: application/json
      x-accepts: application/json
  /api/v2/channel:
    get:
      description: Retrieves all channels related to a Merchant ID.
      security:
      - Hawk:
        - merchant
      summary: List Channels
      tags:
      - Channels
      x-accepts: application/json
    post:
      description: Creates a channel that your end users can openly send payments
        to.
      security:
      - Hawk:
        - merchant
      summary: Create Channel
      tags:
      - Channels
      x-content-type: application/json
      x-accepts: application/json
  /api/v2/channel/{uuid}:
    get:
      description: Retrieves a specific channel by UUID.
      security:
      - Hawk:
        - merchant
      summary: Get Channel
      tags:
      - Channels
      x-accepts: application/json
  /api/v2/channel/payment/{uuid}:
    get:
      description: Retrieves a specific payment made into a channel.
      security:
      - Hawk:
        - merchant
      summary: Get Channel Payment
      tags:
      - Channels
      x-accepts: application/json
  /api/v2/channel/payment:
    get:
      description: Retrieves a list of payments to a channel on a specific Merchant
        ID.
      security:
      - Hawk:
        - merchant
      summary: List Channel Payments
      tags:
      - Channels
      x-accepts: application/json
  /api/wallet:
    get:
      description: Retrieves a list of wallets on your account.
      operationId: walletList
      security:
      - Hawk:
        - user
      summary: List Wallets
      tags:
      - Wallets
      x-accepts: application/json
    post:
      description: Creates a wallet on the BVNK platform.
      operationId: walletCreate
      security:
      - Hawk:
        - user
      summary: Create Wallet
      tags:
      - Wallets
      x-content-type: application/json
      x-accepts: application/json
  /api/wallet/{id}:
    get:
      description: Retrieves a specific wallet.
      operationId: walletRGet
      security:
      - Hawk:
        - user
      summary: Get Wallet
      tags:
      - Wallets
      x-accepts: application/json
  /api/wallet/balances:
    get:
      description: Retrieves the balances of your wallets on platform.
      operationId: walletBalanceList
      security:
      - Hawk:
        - user
      summary: List Wallet Balances
      tags:
      - Wallets
      x-accepts: application/json
  /api/transaction/report:
    get:
      description: Report all transactions from wallet in specified format. Report
        will be generated and sent to main account email in the specified format
      operationId: transactionReport
      security:
      - Hawk:
        - user
      summary: Transactions Report
      tags:
      - Wallets
      x-accepts: application/json
  /api/v1/quote:
    post:
      description: Creates a quote to convert between wallets.
      operationId: quoteCreate
      security:
      - Hawk:
        - merchant
      summary: Create Quote
      tags:
      - Trading and Conversions
      x-content-type: application/json
      x-accepts: application/json
  /api/v1/quote/accept/{uuid}:
    put:
      description: Executes a quote.
      operationId: quoteAccept
      security:
      - Hawk:
        - merchant
      summary: Accept Quote
      tags:
      - Trading and Conversions
      x-accepts: application/json
  /api/v1/quote/{uuid}:
    get:
      description: Retrieves a specific quote.
      operationId: quoteRead
      security:
      - Hawk:
        - merchant
      summary: Read Quote
      tags:
      - Trading and Conversions
      x-accepts: application/json
  /api/v1/quote/{merchantId}:
    get:
      description: Retrieves all quotes on a specific Merchant ID.
      operationId: quoteList
      security:
      - Hawk:
        - x-example
      summary: List Quotes
      tags:
      - Trading and Conversions
      x-accepts: application/json
components:
  securitySchemes:
    Hawk:
      description: "Hawk Payload (see: https://github.com/hueniverse/hawk)"
      in: header
      name: Authorization
      type: apiKey

